const shopData = [
  {
    name: 'Semper Incorporated',
    memberCode: 'SP-114790',
    enrolled: 'May 4, 2022',
    phone: '061-823-2397',
    address: 'Ap #628-731 Pharetra. Ave',
    city: 'Portland',
    state: 'Nevada',
    zip: '57745',
    logo: 'https://dummyimage.com/450x450/969696/393e70.png&text=Img-placeholder',
    companyDescription:
      'ante lectus convallis est, vitae sodales nisi magna sed dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum sodales purus,',
    companyWebsite: 'https://bbc.co.uk',
  },
  {
    name: 'Ac Risus Inc.',
    memberCode: 'SP-85886',
    enrolled: 'Jul 14, 2022',
    phone: '893-375-4273',
    address: 'Ap #381-4666 Eget, St.',
    city: 'Houston',
    state: 'Massachusetts',
    zip: '43293',
    logo: 'https://dummyimage.com/450x450/969696/393e70.png&text=Img-placeholder',
    companyDescription:
      'sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam',
    companyWebsite: 'http://baidu.com',
  },
  {
    name: 'Iaculis Quis LLP',
    memberCode: 'SP-170478',
    enrolled: 'Feb 18, 2022',
    phone: '332-741-7869',
    address: 'P.O. Box 383, 9973 Vehicula Avenue',
    city: 'North Las Vegas',
    state: 'Arkansas',
    zip: '85589',
    logo: 'https://dummyimage.com/450x450/969696/393e70.png&text=Img-placeholder',
    companyDescription:
      'penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum',
    companyWebsite: 'https://nytimes.com',
  },
  {
    name: 'Urna Limited',
    memberCode: 'SP-107774',
    enrolled: 'Dec 22, 2022',
    phone: '554-433-5365',
    address: '299-7639 Cras Street',
    city: 'Southaven',
    state: 'Arkansas',
    zip: '54237',
    logo: 'https://dummyimage.com/450x450/969696/393e70.png&text=Img-placeholder',
    companyDescription:
      'pede, malesuada vel, venenatis vel, faucibus id, libero. Donec consectetuer mauris id sapien. Cras dolor dolor, tempus non, lacinia at,',
    companyWebsite: 'http://guardian.co.uk',
  },
  {
    name: 'Congue Incorporated',
    memberCode: 'SP-108586',
    enrolled: 'May 4, 2022',
    phone: '477-080-0157',
    address: '2530 Euismod Street',
    city: 'Savannah',
    state: 'Louisiana',
    zip: '54643',
    logo: 'https://dummyimage.com/450x450/969696/393e70.png&text=Img-placeholder',
    companyDescription:
      'nec, euismod in, dolor. Fusce feugiat. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam auctor, velit eget laoreet posuere,',
    companyWebsite: 'http://nytimes.com',
  },
  {
    name: 'Turpis Consulting',
    memberCode: 'SP-108466',
    enrolled: 'Jul 31, 2022',
    phone: '824-816-4662',
    address: '868-9676 Aliquam Rd.',
    city: 'Hartford',
    state: 'Montana',
    zip: '54583',
    logo: 'https://dummyimage.com/450x450/969696/393e70.png&text=Img-placeholder',
    companyDescription:
      'a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi.',
    companyWebsite: 'https://netflix.com',
  },
  {
    name: 'Malesuada LLP',
    memberCode: 'SP-59528',
    enrolled: 'Aug 17, 2022',
    phone: '684-956-4628',
    address: '304-6889 Amet, Av.',
    city: 'Augusta',
    state: 'Arkansas',
    zip: '30114',
    logo: 'https://dummyimage.com/450x450/969696/393e70.png&text=Img-placeholder',
    companyDescription:
      'in, cursus et, eros. Proin ultrices. Duis volutpat nunc sit amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt',
    companyWebsite: 'http://baidu.com',
  },
  {
    name: 'Semper Dui Associates',
    memberCode: 'SP-88464',
    enrolled: 'Jul 31, 2022',
    phone: '212-865-6684',
    address: '6996 Mollis. Rd.',
    city: 'Portland',
    state: 'Illinois',
    zip: '44582',
    logo: 'https://dummyimage.com/450x450/969696/393e70.png&text=Img-placeholder',
    companyDescription:
      'Nulla eget metus eu erat semper rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu',
    companyWebsite: 'https://zoom.us',
  },
  {
    name: 'Cras Eget Incorporated',
    memberCode: 'SP-98188',
    enrolled: 'Aug 31, 2022',
    phone: '760-399-4461',
    address: '984-7672 Eu Rd.',
    city: 'Birmingham',
    state: 'California',
    zip: '49444',
    logo: 'https://dummyimage.com/450x450/969696/393e70.png&text=Img-placeholder',
    companyDescription:
      'lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis',
    companyWebsite: 'http://bbc.co.uk',
  },
  {
    name: 'Enim Diam Industries',
    memberCode: 'SP-185578',
    enrolled: 'Jul 11, 2021',
    phone: '559-021-4497',
    address: '138-4129 Erat Rd.',
    city: 'Lafayette',
    state: 'Idaho',
    zip: '93139',
    logo: 'https://dummyimage.com/450x450/969696/393e70.png&text=Img-placeholder',
    companyDescription:
      'mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras',
    companyWebsite: 'https://guardian.co.uk',
  },
  {
    name: 'Egestas Incorporated',
    memberCode: 'SP-25862',
    enrolled: 'Dec 11, 2021',
    phone: '573-544-4080',
    address: '180-7420 Curae Road',
    city: 'West Jordan',
    state: 'Alaska',
    zip: '13281',
    logo: 'https://dummyimage.com/450x450/969696/393e70.png&text=Img-placeholder',
    companyDescription:
      'amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla. Integer vulputate, risus a ultricies adipiscing, enim',
    companyWebsite: 'http://guardian.co.uk',
  },
  {
    name: 'Ante Company',
    memberCode: 'SP-141808',
    enrolled: 'Apr 20, 2022',
    phone: '288-228-6185',
    address: '3508 Integer Road',
    city: 'West Valley City',
    state: 'Arizona',
    zip: '71254',
    logo: 'https://dummyimage.com/450x450/969696/393e70.png&text=Img-placeholder',
    companyDescription:
      'tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque',
    companyWebsite: 'http://baidu.com',
  },
  {
    name: 'Aliquam Erat Industries',
    memberCode: 'SP-85762',
    enrolled: 'Dec 1, 2022',
    phone: '452-466-0465',
    address: '3464 Pellentesque Avenue',
    city: 'Sioux City',
    state: 'Maine',
    zip: '43231',
    logo: 'https://dummyimage.com/450x450/969696/393e70.png&text=Img-placeholder',
    companyDescription:
      'porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit',
    companyWebsite: 'http://baidu.com',
  },
  {
    name: 'Dolor Tempus Non Incorporated',
    memberCode: 'SP-155986',
    enrolled: 'Oct 15, 2022',
    phone: '577-724-5113',
    address: '569-4028 Diam St.',
    city: 'Hilo',
    state: 'Maryland',
    zip: '78343',
    logo: 'https://dummyimage.com/450x450/969696/393e70.png&text=Img-placeholder',
    companyDescription:
      'Cras convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat semper rutrum.',
    companyWebsite: 'https://facebook.com',
  },
  {
    name: 'Sem Semper Corp.',
    memberCode: 'SP-44764',
    enrolled: 'Jan 13, 2023',
    phone: '453-877-6550',
    address: '275-4290 Pede Road',
    city: 'Independence',
    state: 'Minnesota',
    zip: '22732',
    logo: 'https://dummyimage.com/450x450/969696/393e70.png&text=Img-placeholder',
    companyDescription:
      'Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices',
    companyWebsite: 'https://facebook.com',
  },
  {
    name: 'Lacinia Mattis LLP',
    memberCode: 'SP-43964',
    enrolled: 'Mar 7, 2022',
    phone: '847-822-3544',
    address: '340-1842 Non Road',
    city: 'Iowa City',
    state: 'Washington',
    zip: '22332',
    logo: 'https://dummyimage.com/450x450/969696/393e70.png&text=Img-placeholder',
    companyDescription:
      'malesuada vel, venenatis vel, faucibus id, libero. Donec consectetuer mauris id sapien. Cras dolor dolor, tempus non, lacinia at, iaculis',
    companyWebsite: 'http://instagram.com',
  },
  {
    name: 'Dui Cum Foundation',
    memberCode: 'SP-70410',
    enrolled: 'Sep 5, 2022',
    phone: '164-503-4813',
    address: '252-3359 Felis St.',
    city: 'Fairbanks',
    state: 'Delaware',
    zip: '35555',
    logo: 'https://dummyimage.com/450x450/969696/393e70.png&text=Img-placeholder',
    companyDescription:
      'gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis',
    companyWebsite: 'https://whatsapp.com',
  },
  {
    name: 'Velit Aliquam Incorporated',
    memberCode: 'SP-95530',
    enrolled: 'May 19, 2023',
    phone: '685-581-1517',
    address: '1848 Mi Street',
    city: 'Saint Louis',
    state: 'Vermont',
    zip: '48115',
    logo: 'https://dummyimage.com/450x450/969696/393e70.png&text=Img-placeholder',
    companyDescription:
      'ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non',
    companyWebsite: 'http://nytimes.com',
  },
  {
    name: 'Eu Enim Etiam LLP',
    memberCode: 'SP-108936',
    enrolled: 'Aug 4, 2021',
    phone: '364-758-1718',
    address: '1849 Donec St.',
    city: 'San Antonio',
    state: 'Nevada',
    zip: '54818',
    logo: 'https://dummyimage.com/450x450/969696/393e70.png&text=Img-placeholder',
    companyDescription:
      'magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit viverra. Donec tempus, lorem',
    companyWebsite: 'https://nytimes.com',
  },
  {
    name: 'Accumsan Industries',
    memberCode: 'SP-88774',
    enrolled: 'Jul 3, 2022',
    phone: '724-422-1712',
    address: 'Ap #226-2936 Facilisi. St.',
    city: 'Bridgeport',
    state: 'Massachusetts',
    zip: '44737',
    logo: 'https://dummyimage.com/450x450/969696/393e70.png&text=Img-placeholder',
    companyDescription:
      'quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at',
    companyWebsite: 'http://bbc.co.uk',
  },
];
